Repository probberechts/soccerdata, pull requests merged in 2024-02, with the labels that each got.

#461 Add support for scraping FotMob
  .github/labels.yml
  README.rst
  docs/datasources/FotMob.ipynb
  docs/datasources/index.rst
  docs/howto/custom-leagues.rst
  docs/index.rst
  docs/reference/fotmob.rst
  docs/reference/index.rst
  soccerdata/__init__.py
  soccerdata/_config.py
  soccerdata/fbref.py
  soccerdata/fotmob.py
  tests/conftest.py
  tests/test_FotMob.py
Labels: enhancement

#473 Update dependency black to v24
  README.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  soccerdata/clubelo.py
  soccerdata/espn.py
  soccerdata/fbref.py
  soccerdata/fivethirtyeight.py
  soccerdata/fotmob.py
  soccerdata/match_history.py
  soccerdata/sofifa.py
  soccerdata/whoscored.py
  tests/conftest.py
  tests/test_ClubElo.py
  tests/test_ESPN.py
  tests/test_FBref.py
  tests/test_SoFIFA.py
  tests/test_Whoscored.py
  tests/test_config.py
Labels: dependencies

#481 [Nox] Replace tilde with Path.home()
  noxfile.py
Labels: build

#490 [ESPN] Allow new roster format
  soccerdata/espn.py
Labels: bug, ESPN
